//! Events emitted by the physics simulation (blueprint §5.4 sound hooks, §10.6).
//!
//! The spin "click track" is generated by the sim, not scripted: a future renderer
//! or `SoundManager` consumes this stream (`playRouletteClick` per divider tick,
//! `playPegBounce` on deflector hits).

use serde::{Deserialize, Serialize};

/// One physics event, emitted in deterministic order during `step()`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum SimEvent {
    /// A deflector pin was struck by the identified ball (§5.4 `playPegBounce`).
    PegHit { ball: u32 },
    /// A divider/peg tick passed under the identified ball (§5.4 `playRouletteClick`).
    DividerTick { ball: u32 },
    /// The identified ball locked into `slot` (slot index into wheel numbers).
    BallSettled { ball: u32, slot: usize },
    /// The identified ball hit the step cap without settling (§10.6 60 s limit).
    SettleTimeout { ball: u32 },
    /// The shotgun timer fired: `count` extra balls spawned mid-spin (§5.3).
    ShotgunFired { count: u32 },
    /// A split-peg ball duplication produced one extra ball (§5.3).
    BallSplit { ball: u32 },
}

impl SimEvent {
    /// Stable discriminator for hashing event logs in golden tests (TEST-001).
    pub fn tag(&self) -> u8 {
        match self {
            SimEvent::PegHit { .. } => 1,
            SimEvent::DividerTick { .. } => 2,
            SimEvent::BallSettled { .. } => 3,
            SimEvent::SettleTimeout { .. } => 4,
            SimEvent::ShotgunFired { .. } => 5,
            SimEvent::BallSplit { .. } => 6,
        }
    }
}
